export const metadata = {
    title: 'Product Details',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
        {children}
        <h2>Product page rendered within children above</h2>
      </>
    )
  }